# Site settings
title: Kumar Ayush
email: cheekujodhpur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an everyday data scientist and developer who likes to turn dreams into reality. My magical staff is called an undergraduate degree in Physics mixed with experience in astronomy, web development, computer graphics and management.

description_small: turns dreams into reality.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cheekujodhpur.github.io" # the base hostname & protocol for your site
social:
    twitter: https://twitter.com/kumarayush4ever
    github: https://github.com/cheekujodhpur
    linkedin-square: https://linkedin.com/in/cheekujodhpur
    facebook-official: https://facebook.com/cheekujodhpur
    google-plus-square: https://plus.google.com/u/0/+cheekujodhpur

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['spectral','_pages/elements.html', '_pages/generic.html']
kramdown:
  input: GFM
  parse_block_html: true
collections:
  projects:
    output: true
  bposts:
    output: true
#   showcase_projects:
#     output: true
#   events:
#     output: true

