# Site settings
title: Kumar Ayush
email: cheekujodhpur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official website for Kumar Ayush.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "kumarayush.com" # the base hostname & protocol for your site
twitter_username: kumarayush4ever
github_username:  cheekujodhpur
facebook_username: cheekujodhpur
linkedin_username: cheekujodhpur

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
# collections:
#   soc_projects:
#     output: true
#   showcase_projects:
#     output: true
#   events:
#     output: true

