# Site settings
title: Kumar Ayush
email: cheekujodhpur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  background in physics, works in finance as a quant. likes to read history and poltics. blogs, plays violin not bad but not very good. fun guy, turns dreams into reality.
 
description_small: turns dreams into reality.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kumar-ayush.com" # the base hostname & protocol for your site
social:
    github: https://github.com/cheekujodhpur
    linkedin-square: https://linkedin.com/in/cheekujodhpur
    twitter: https://twitter.com/kumarayush4ever
    facebook-official: https://facebook.com/cheekujodhpur

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['Gemfile', 'Gemfile.lock', 'Makefile', 'spectral','_pages/elements.html', '_pages/generic.html']
kramdown:
  input: GFM
  parse_block_html: true
collections:
  projects:
    output: true
  bposts:
    output: true
#   showcase_projects:
#     output: true
#   events:
#     output: true

timezone: Asia/Calcutta
future: true
